"""Chat with Vietnamese company-law documents using RAG and Qwen.

This script retrieves relevant legal chunks from the vector store generated by
step2_build_vectorstore.py, then asks a Qwen model to answer with citations.

Default generation backend: Ollama at http://localhost:11434 with qwen3:4b.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from dataclasses import dataclass
from importlib import import_module
from pathlib import Path
from typing import Any

import numpy as np
import requests


DEFAULT_VECTORSTORE = Path("vectorstore") / "legal_vectorstore.json"
DEFAULT_OLLAMA_URL = "http://localhost:11434"
DEFAULT_QWEN_MODEL = "qwen3:4b"
DEFAULT_TOP_K = 5
DEDUP_CANDIDATE_MULTIPLIER = 4


@dataclass
class RetrievedChunk:
    rank: int
    score: float
    chunk_id: str
    text: str
    metadata: dict[str, Any]


def configure_console_encoding() -> None:
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if callable(reconfigure):
            reconfigure(encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="RAG chatbot for Vietnamese company law")
    parser.add_argument("--vectorstore", default=str(DEFAULT_VECTORSTORE), help="Path to vector store JSON")
    parser.add_argument("--question", help="Ask one question and exit")
    parser.add_argument("--top-k", type=int, default=DEFAULT_TOP_K, help="Number of chunks to retrieve")
    parser.add_argument("--model", default=os.getenv("QWEN_MODEL", DEFAULT_QWEN_MODEL), help="Qwen model name")
    parser.add_argument(
        "--ollama-url",
        default=os.getenv("OLLAMA_URL", DEFAULT_OLLAMA_URL),
        help="Ollama server URL",
    )
    parser.add_argument("--temperature", type=float, default=0.2, help="Generation temperature")
    parser.add_argument("--max-context-chars", type=int, default=12000, help="Maximum retrieved context size")
    parser.add_argument("--retrieve-only", action="store_true", help="Only show retrieved chunks; do not call Qwen")
    args = parser.parse_args()

    if args.top_k <= 0:
        parser.error("--top-k must be greater than 0")
    if args.max_context_chars <= 500:
        parser.error("--max-context-chars must be greater than 500")
    return args


def load_vectorstore(path: Path) -> tuple[dict[str, Any], list[dict[str, Any]], np.ndarray]:
    if not path.exists():
        raise FileNotFoundError(
            f"Vector store not found: {path}. Run: python step2_build_vectorstore.py"
        )

    with path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)

    manifest = payload.get("manifest")
    documents = payload.get("documents")
    if not isinstance(manifest, dict) or not isinstance(documents, list):
        raise ValueError("Vector store must contain manifest and documents")
    if manifest.get("vector_type") != "dense_embedding":
        raise ValueError("This chatbot requires a dense_embedding vector store")
    if not documents:
        raise ValueError("Vector store has no documents")

    if len(documents) < 20:
        print(
            f"\n[⚠️ CẢNH BÁO] Vector store chỉ chứa {len(documents)} documents (quá ít!)."
            "\n              Chatbot có thể trả lời không chính xác do thiếu dữ liệu.\n"
        )

    vectors = np.array([doc["vector"] for doc in documents], dtype=np.float32)
    if vectors.ndim != 2:
        raise ValueError("Document vectors must be a 2D array")

    return manifest, documents, vectors


def load_embedding_model(model_name: str):
    try:
        SentenceTransformer = import_module("sentence_transformers").SentenceTransformer
    except ImportError as exc:
        raise RuntimeError("Missing dependency: sentence-transformers") from exc
    return SentenceTransformer(model_name)


def encode_query(model: Any, question: str, model_name: str) -> np.ndarray:
    text = f"query: {question}" if "e5" in model_name.lower() else question
    vector = model.encode([text], normalize_embeddings=True, show_progress_bar=False)[0]
    return np.array(vector, dtype=np.float32)


def dedupe_key(text: str) -> str:
    compact = re.sub(r"\s+", " ", text).strip().lower()
    return compact[:1200]


def retrieve(
    question: str,
    model: Any,
    model_name: str,
    documents: list[dict[str, Any]],
    vectors: np.ndarray,
    top_k: int,
) -> list[RetrievedChunk]:
    query_vector = encode_query(model, question, model_name)
    scores = vectors @ query_vector
    candidate_count = min(len(documents), top_k * DEDUP_CANDIDATE_MULTIPLIER)
    top_indexes = sorted(range(len(scores)), key=lambda index: (-float(scores[index]), index))[:candidate_count]

    results: list[RetrievedChunk] = []
    seen_texts: set[str] = set()
    for index in top_indexes:
        doc = documents[int(index)]
        key = dedupe_key(str(doc["noi_dung"]))
        if key in seen_texts:
            continue
        seen_texts.add(key)
        results.append(
            RetrievedChunk(
                rank=len(results) + 1,
                score=float(scores[int(index)]),
                chunk_id=str(doc["chunk_id"]),
                text=str(doc["noi_dung"]),
                metadata=dict(doc.get("metadata") or {}),
            )
        )
        if len(results) == top_k:
            break
    return results


def format_source(chunk: RetrievedChunk) -> str:
    meta = chunk.metadata
    law = meta.get("so_hieu") or "không rõ số hiệu"
    article = meta.get("so_dieu") or "không rõ điều"
    title = meta.get("ten_dieu") or ""
    return f"[{chunk.rank}] {law}, {article}" + (f" - {title}" if title else "")


def build_context(chunks: list[RetrievedChunk], max_chars: int) -> str:
    parts: list[str] = []
    used = 0
    for chunk in chunks:
        source = format_source(chunk)
        text = chunk.text.strip()
        block = f"{source}\n{text}"
        remaining = max_chars - used
        if remaining <= 0:
            break
        if len(block) > remaining:
            block = block[:remaining].rstrip()
        parts.append(block)
        used += len(block)
    return "\n\n---\n\n".join(parts)


def build_messages(question: str, chunks: list[RetrievedChunk], max_context_chars: int) -> list[dict[str, str]]:
    context = build_context(chunks, max_context_chars)
    system = (
        "Bạn là chatbot RAG hỗ trợ tra cứu pháp luật doanh nghiệp Việt Nam. "
        "Chỉ trả lời dựa trên NGỮ CẢNH được cung cấp. Nếu ngữ cảnh không đủ, "
        "hãy nói rõ là chưa đủ căn cứ. Không bịa điều luật. Luôn trích dẫn nguồn "
        "theo dạng [1], [2] tương ứng với các đoạn ngữ cảnh."
    )
    user = (
        f"NGỮ CẢNH:\n{context}\n\n"
        f"CÂU HỎI:\n{question}\n\n"
        "Hãy trả lời ngắn gọn, chính xác, có trích dẫn."
    )
    return [{"role": "system", "content": system}, {"role": "user", "content": user}]


def call_ollama(
    messages: list[dict[str, str]],
    model: str,
    ollama_url: str,
    temperature: float,
) -> str:
    url = ollama_url.rstrip("/") + "/api/chat"
    response = requests.post(
        url,
        json={
            "model": model,
            "messages": messages,
            "stream": False,
            "options": {"temperature": temperature},
        },
        timeout=180,
    )
    response.raise_for_status()
    payload = response.json()
    message = payload.get("message") or {}
    content = message.get("content")
    if not content:
        raise RuntimeError(f"Ollama returned an unexpected response: {payload}")
    return str(content).strip()


def print_retrieved(chunks: list[RetrievedChunk]) -> None:
    print("\nNguồn truy xuất:")
    for chunk in chunks:
        print(f"  {format_source(chunk)} | score={chunk.score:.4f} | chunk_id={chunk.chunk_id}")


def answer_question(args: argparse.Namespace, model: Any, manifest: dict[str, Any], documents: list[dict[str, Any]], vectors: np.ndarray, question: str) -> None:
    chunks = retrieve(question, model, manifest["embedding_model"], documents, vectors, args.top_k)
    print_retrieved(chunks)

    if args.retrieve_only:
        print("\nCác đoạn liên quan:")
        for chunk in chunks:
            preview = chunk.text.strip().replace("\n", " ")
            print(f"\n{format_source(chunk)}\n{preview[:1000]}")
        return

    messages = build_messages(question, chunks, args.max_context_chars)
    try:
        answer = call_ollama(messages, args.model, args.ollama_url, args.temperature)
    except requests.RequestException as exc:
        raise RuntimeError(
            f"Cannot call Qwen via Ollama at {args.ollama_url}. "
            f"Start Ollama and run: ollama pull {args.model}"
        ) from exc

    print("\nTrả lời:")
    print(answer)


def chat_loop(args: argparse.Namespace, model: Any, manifest: dict[str, Any], documents: list[dict[str, Any]], vectors: np.ndarray) -> None:
    print("RAG chatbot đã sẵn sàng. Gõ 'exit' để thoát.")
    while True:
        question = input("\nBạn hỏi: ").strip()
        if question.lower() in {"exit", "quit", "q"}:
            break
        if not question:
            continue
        answer_question(args, model, manifest, documents, vectors, question)


def main() -> None:
    configure_console_encoding()
    args = parse_args()
    manifest, documents, vectors = load_vectorstore(Path(args.vectorstore))
    model = load_embedding_model(manifest["embedding_model"])

    if args.question:
        answer_question(args, model, manifest, documents, vectors, args.question)
    else:
        chat_loop(args, model, manifest, documents, vectors)


if __name__ == "__main__":
    try:
        main()
    except (FileNotFoundError, RuntimeError, ValueError) as exc:
        raise SystemExit(str(exc)) from exc
