"""Chat with Vietnamese company-law documents using RAG and Qwen.

This script retrieves relevant legal chunks from the vector store generated by
step2_build_vectorstore.py, then asks a Qwen model to answer with citations.

Default generation backend: Ollama at http://localhost:11434 with qwen3:4b.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import unicodedata
from dataclasses import dataclass
from importlib import import_module
from pathlib import Path
from typing import Any

import numpy as np
import requests


DEFAULT_VECTORSTORE = Path("vectorstore") / "legal_vectorstore.json"
DEFAULT_OLLAMA_URL = "http://localhost:11434"
DEFAULT_QWEN_MODEL = "qwen3:4b"
DEFAULT_TOP_K = 5
DEDUP_CANDIDATE_MULTIPLIER = 4
FALLBACK_ANSWER = "Không tìm thấy thông tin trong tài liệu được cung cấp."
DEFAULT_MIN_RETRIEVAL_SCORE = float(os.getenv("MIN_RETRIEVAL_SCORE", "0.84"))
DEFAULT_MIN_TOP_GAP = float(os.getenv("MIN_TOP_GAP", "0.008"))
DEFAULT_MAX_SCORE_DROP = float(os.getenv("MAX_SCORE_DROP", "0.08"))

LEGAL_DOMAIN_TERMS = (
    "doanh nghiep",
    "cong ty",
    "ho kinh doanh",
    "dang ky",
    "thanh lap",
    "giai the",
    "pha san",
    "tam ngung",
    "von dieu le",
    "von gop",
    "co phan",
    "co dong",
    "thanh vien",
    "nguoi dai dien",
    "giay chung nhan",
    "ho so",
    "chi nhanh",
    "van phong dai dien",
    "dia diem kinh doanh",
    "doanh nghiep tu nhan",
    "hop danh",
    "trach nhiem huu han",
    "mau so",
    "phu luc",
    "nghi dinh",
    "thong tu",
    "luat doanh nghiep",
)

VAGUE_QUESTION_PATTERNS = (
    r"^(cai|viec|van de) (nay|do) (la gi|lam sao|the nao)?\??$",
    r"^(lam sao|the nao|gi vay|sao day)\??$",
    r"^(dang ky doanh nghiep|thanh lap doanh nghiep|mo cong ty)\??$",
)

ADVICE_PATTERNS = (
    r"\btoi nen\b",
    r"\bco nen\b",
    r"\bnen chon\b",
    r"\bnen lam gi\b",
    r"\btu van\b",
)

TOKEN_REWRITES = {
    "đăg": "đăng",
    "đag": "đăng",
    "đăngg": "đăng",
    "kí": "ký",
    "doang": "doanh",
    "ngiệp": "nghiệp",
    "nghiêp": "nghiệp",
    "côg": "công",
    "cty": "công ty",
}


@dataclass
class RetrievedChunk:
    rank: int
    score: float
    chunk_id: str
    text: str
    metadata: dict[str, Any]


@dataclass
class QueryAnalysis:
    original_question: str
    retrieval_question: str
    should_retrieve: bool
    reason: str
    has_strong_legal_signal: bool


@dataclass
class RetrievalResult:
    chunks: list[RetrievedChunk]
    query: QueryAnalysis
    accepted: bool
    reason: str
    top_score: float | None = None
    top_gap: float | None = None


def configure_console_encoding() -> None:
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if callable(reconfigure):
            reconfigure(encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="RAG chatbot for Vietnamese company law")
    parser.add_argument("--vectorstore", default=str(DEFAULT_VECTORSTORE), help="Path to vector store JSON")
    parser.add_argument("--question", help="Ask one question and exit")
    parser.add_argument("--top-k", type=int, default=DEFAULT_TOP_K, help="Number of chunks to retrieve")
    parser.add_argument("--model", default=os.getenv("QWEN_MODEL", DEFAULT_QWEN_MODEL), help="Qwen model name")
    parser.add_argument(
        "--ollama-url",
        default=os.getenv("OLLAMA_URL", DEFAULT_OLLAMA_URL),
        help="Ollama server URL",
    )
    parser.add_argument("--temperature", type=float, default=0.2, help="Generation temperature")
    parser.add_argument("--max-context-chars", type=int, default=12000, help="Maximum retrieved context size")
    parser.add_argument("--retrieve-only", action="store_true", help="Only show retrieved chunks; do not call Qwen")
    args = parser.parse_args()

    if args.top_k <= 0:
        parser.error("--top-k must be greater than 0")
    if args.max_context_chars <= 500:
        parser.error("--max-context-chars must be greater than 500")
    return args


def load_vectorstore(path: Path) -> tuple[dict[str, Any], list[dict[str, Any]], np.ndarray]:
    if not path.exists():
        raise FileNotFoundError(
            f"Vector store not found: {path}. Run: python step2_build_vectorstore.py"
        )

    with path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)

    manifest = payload.get("manifest")
    documents = payload.get("documents")
    if not isinstance(manifest, dict) or not isinstance(documents, list):
        raise ValueError("Vector store must contain manifest and documents")
    if manifest.get("vector_type") != "dense_embedding":
        raise ValueError("This chatbot requires a dense_embedding vector store")
    if not documents:
        raise ValueError("Vector store has no documents")

    if len(documents) < 20:
        print(
            f"\n[⚠️ CẢNH BÁO] Vector store chỉ chứa {len(documents)} documents (quá ít!)."
            "\n              Chatbot có thể trả lời không chính xác do thiếu dữ liệu.\n"
        )

    vectors = np.array([doc["vector"] for doc in documents], dtype=np.float32)
    if vectors.ndim != 2:
        raise ValueError("Document vectors must be a 2D array")

    return manifest, documents, vectors


def load_embedding_model(model_name: str):
    try:
        SentenceTransformer = import_module("sentence_transformers").SentenceTransformer
    except ImportError as exc:
        raise RuntimeError("Missing dependency: sentence-transformers") from exc
    return SentenceTransformer(model_name)


def encode_query(model: Any, question: str, model_name: str) -> np.ndarray:
    text = f"query: {question}" if "e5" in model_name.lower() else question
    vector = model.encode([text], normalize_embeddings=True, show_progress_bar=False)[0]
    return np.array(vector, dtype=np.float32)


def normalize_for_match(text: str) -> str:
    no_accents = "".join(
        char
        for char in unicodedata.normalize("NFD", text)
        if unicodedata.category(char) != "Mn"
    )
    no_accents = no_accents.replace("đ", "d").replace("Đ", "D")
    return re.sub(r"\s+", " ", no_accents.lower()).strip()


def rewrite_query(question: str) -> str:
    """Clean up obvious typos/noise without adding new legal meaning."""
    rewritten = re.sub(r"\s+", " ", question).strip()
    normalized_words = normalize_for_match(rewritten).split()

    # Keep the clause after an explicit transition from small talk.
    for marker in ("tien the", "nhan tien", "cho toi hoi"):
        marker_words = marker.split()
        for index in range(len(normalized_words) - len(marker_words), -1, -1):
            if normalized_words[index : index + len(marker_words)] == marker_words:
                rewritten = " ".join(rewritten.split()[index + len(marker_words) :]).strip(" ,;:-")
                normalized_words = normalize_for_match(rewritten).split()
                break
        else:
            continue
        break

    polite_prefixes = (
        r"^cho tôi biết\s+",
        r"^xin cho biết\s+",
        r"^vui lòng cho biết\s+",
        r"^tôi muốn hỏi\s+",
    )
    for pattern in polite_prefixes:
        cleaned = re.sub(pattern, "", rewritten, flags=re.IGNORECASE)
        if cleaned != rewritten:
            rewritten = cleaned.strip()
            break

    corrected: list[str] = []
    for word in rewritten.split():
        match = re.match(r"^([^\wÀ-ỹĐđ]*)(.*?)([^\wÀ-ỹĐđ]*)$", word, flags=re.UNICODE)
        if not match:
            corrected.append(word)
            continue
        prefix, core, suffix = match.groups()
        corrected.append(f"{prefix}{TOKEN_REWRITES.get(core.lower(), core)}{suffix}")
    return re.sub(r"\s+", " ", " ".join(corrected)).strip()


def analyze_question(question: str) -> QueryAnalysis:
    original = re.sub(r"\s+", " ", question).strip()
    rewritten = rewrite_query(original)
    normalized = normalize_for_match(rewritten)
    tokens = re.findall(r"\b\w+\b", normalized, flags=re.UNICODE)
    has_domain_term = any(term in normalized for term in LEGAL_DOMAIN_TERMS)
    has_legal_identifier = bool(
        re.search(r"\b\d{1,4}/\d{4}/[a-z]+(?:-[a-z]+)?\b", normalized)
        or re.search(r"\bdieu\s+\d+\b", normalized)
    )
    has_strong_signal = has_legal_identifier or any(
        term in normalized
        for term in (
            "doanh nghiep",
            "cong ty",
            "ho kinh doanh",
            "luat doanh nghiep",
            "mau so",
            "phu luc",
        )
    )

    if not original:
        return QueryAnalysis(original, rewritten, False, "empty_question", False)
    if len(tokens) < 2:
        return QueryAnalysis(original, rewritten, False, "too_short", has_strong_signal)
    if any(re.fullmatch(pattern, normalized) for pattern in VAGUE_QUESTION_PATTERNS):
        return QueryAnalysis(original, rewritten, False, "ambiguous_question", has_strong_signal)
    if not has_domain_term and not has_legal_identifier:
        return QueryAnalysis(original, rewritten, False, "out_of_scope", False)
    if any(re.search(pattern, normalized) for pattern in ADVICE_PATTERNS):
        concrete_terms = (
            "ho so",
            "dieu kien",
            "thu tuc",
            "thoi han",
            "quyen",
            "nghia vu",
            "cam",
            "khong duoc",
            "mau so",
            "phu luc",
        )
        if not any(term in normalized for term in concrete_terms):
            return QueryAnalysis(
                original,
                rewritten,
                False,
                "advice_without_legal_fact",
                has_strong_signal,
            )

    return QueryAnalysis(original, rewritten, True, "accepted", has_strong_signal)


def keyword_boost(question: str, doc: dict[str, Any]) -> float:
    """Small deterministic boost for legal citations and form numbers.

    Dense embeddings are good for meaning, but legal/form questions often hinge
    on exact tokens such as "Mẫu số 1" or "Phụ lục I".
    """
    query = normalize_for_match(question)
    metadata = doc.get("metadata") or {}
    fields = normalize_for_match(
        " ".join(
            str(value)
            for value in (
                metadata.get("so_hieu"),
                metadata.get("chuong"),
                metadata.get("ten_chuong"),
                metadata.get("so_dieu"),
                metadata.get("ten_dieu"),
                doc.get("noi_dung", "")[:500],
            )
            if value
        )
    )

    boost = 0.0
    for law_id in re.findall(r"\b\d{1,4}/\d{4}/[a-z]+(?:-[a-z]+)?\b", query):
        if law_id in fields:
            boost += 0.04

    form_match = re.search(r"\bmau\s+so\s+(\d+)\b", query)
    if form_match and re.search(rf"\bmau\s+so\s+0*{form_match.group(1)}\b", fields):
        boost += 0.12
        # When asking for a specific form, prefer the extracted DOCX form body
        # over the circular's HTML appendix list.
        if metadata.get("nguon") == "docx":
            boost += 0.06
        elif metadata.get("nguon") == "html":
            boost -= 0.03

    appendix_match = re.search(r"\bphu\s+luc\s+([ivx]+)\b", query)
    if appendix_match:
        requested_appendix = appendix_match.group(1)
        if re.search(rf"\bphu\s+luc\s+{requested_appendix}\b", fields):
            boost += 0.08
        elif re.search(r"\bphu\s+luc\s+[ivx]+\b", fields):
            boost -= 0.06

    title_terms = [
        "giay de nghi dang ky ho kinh doanh",
        "giay de nghi dang ky doanh nghiep",
        "thong bao cham dut",
        "tam ngung kinh doanh",
        "cap lai giay chung nhan",
        "khong duoc thanh lap",
    ]
    for term in title_terms:
        if term in query and term in fields:
            boost += 0.06
    if "khong duoc thanh lap" in query and "khong co quyen thanh lap" in fields:
        boost += 0.10
    return boost


def dedupe_key(text: str) -> str:
    compact = re.sub(r"\s+", " ", text).strip().lower()
    return compact[:1200]


def retrieve(
    question: str,
    model: Any,
    model_name: str,
    documents: list[dict[str, Any]],
    vectors: np.ndarray,
    top_k: int,
) -> list[RetrievedChunk]:
    query_vector = encode_query(model, question, model_name)
    dense_scores = vectors @ query_vector
    boosts = np.array([keyword_boost(question, doc) for doc in documents], dtype=np.float32)
    scores = dense_scores + boosts
    candidate_count = min(len(documents), top_k * DEDUP_CANDIDATE_MULTIPLIER)
    top_indexes = sorted(range(len(scores)), key=lambda index: (-float(scores[index]), index))[:candidate_count]

    results: list[RetrievedChunk] = []
    seen_texts: set[str] = set()
    for index in top_indexes:
        doc = documents[int(index)]
        key = dedupe_key(str(doc["noi_dung"]))
        if key in seen_texts:
            continue
        seen_texts.add(key)
        results.append(
            RetrievedChunk(
                rank=len(results) + 1,
                score=float(scores[int(index)]),
                chunk_id=str(doc["chunk_id"]),
                text=str(doc["noi_dung"]),
                metadata=dict(doc.get("metadata") or {}),
            )
        )
        if len(results) == top_k:
            break
    return results


def guarded_retrieve(
    question: str,
    model: Any,
    model_name: str,
    documents: list[dict[str, Any]],
    vectors: np.ndarray,
    top_k: int,
    min_score: float = DEFAULT_MIN_RETRIEVAL_SCORE,
    min_top_gap: float = DEFAULT_MIN_TOP_GAP,
    max_score_drop: float = DEFAULT_MAX_SCORE_DROP,
) -> RetrievalResult:
    query = analyze_question(question)
    if not query.should_retrieve:
        return RetrievalResult([], query, False, query.reason)

    candidates = retrieve(
        query.retrieval_question,
        model,
        model_name,
        documents,
        vectors,
        top_k,
    )
    if not candidates:
        return RetrievalResult([], query, False, "no_candidates")

    top_score = candidates[0].score
    top_gap = top_score - candidates[1].score if len(candidates) > 1 else top_score
    if top_score < min_score:
        return RetrievalResult([], query, False, "score_below_threshold", top_score, top_gap)

    # Close scores are normal for explicit legal citations or concrete subjects,
    # but otherwise indicate that retrieval has no confident best match.
    if top_gap < min_top_gap and not query.has_strong_legal_signal:
        return RetrievalResult([], query, False, "top_results_too_close", top_score, top_gap)

    filtered = [
        chunk
        for chunk in candidates
        if chunk.score >= min_score and (top_score - chunk.score) <= max_score_drop
    ]
    if not filtered:
        return RetrievalResult([], query, False, "no_chunk_after_filter", top_score, top_gap)

    for rank, chunk in enumerate(filtered, 1):
        chunk.rank = rank
    return RetrievalResult(filtered, query, True, "accepted", top_score, top_gap)


def format_source(chunk: RetrievedChunk) -> str:
    meta = chunk.metadata
    law = meta.get("so_hieu") or "không rõ số hiệu"
    article = meta.get("so_dieu") or "không rõ điều"
    title = meta.get("ten_dieu") or ""
    return f"[{chunk.rank}] {law}, {article}" + (f" - {title}" if title else "")


def build_context(chunks: list[RetrievedChunk], max_chars: int) -> str:
    parts: list[str] = []
    used = 0
    for chunk in chunks:
        source = format_source(chunk)
        text = chunk.text.strip()
        block = f"{source}\n{text}"
        remaining = max_chars - used
        if remaining <= 0:
            break
        if len(block) > remaining:
            block = block[:remaining].rstrip()
        parts.append(block)
        used += len(block)
    return "\n\n---\n\n".join(parts)


def build_messages(question: str, chunks: list[RetrievedChunk], max_context_chars: int) -> list[dict[str, str]]:
    context = build_context(chunks, max_context_chars)
    system = (
        "/no_think\n"
        "Bạn là hệ thống hỏi đáp và trích xuất thông tin pháp luật doanh nghiệp Việt Nam. "
        "Chỉ xuất câu trả lời cuối cùng bằng tiếng Việt. Không hiển thị quá trình suy luận, "
        "phân tích context, bản dịch câu hỏi hoặc lời dẫn như 'Okay, let's tackle'. "
        "Chỉ được trả lời dựa trên CONTEXT được cung cấp; không sử dụng kiến thức bên ngoài "
        "và không suy đoán. Chỉ trình bày quy định có liên quan trong CONTEXT. "
        "Không đưa ra lời khuyên, chiến lược xử lý, khuyến nghị lựa chọn hoặc kết luận pháp lý "
        "cho trường hợp cụ thể. Không tự thêm tên văn bản, số điều, khoản hoặc điểm nếu CONTEXT "
        "không chứa thông tin đó. Mỗi thông tin pháp lý phải có trích dẫn [1], [2] tương ứng "
        f"với chunk nguồn. Nếu CONTEXT không đủ để trả lời, chỉ trả lời đúng câu: \"{FALLBACK_ANSWER}\""
    )
    user = (
        f"CONTEXT:\n{context}\n\n"
        f"CÂU HỎI:\n{question}\n\n"
        "Chỉ xuất câu trả lời cuối cùng bằng tiếng Việt, bắt đầu trực tiếp bằng nội dung trả lời. "
        "Không mô tả cách bạn đọc hoặc phân tích CONTEXT. "
        "Hãy trả lời ngắn gọn, chính xác và chỉ trích xuất thông tin có trong CONTEXT.\n/no_think"
    )
    return [{"role": "system", "content": system}, {"role": "user", "content": user}]


def call_ollama(
    messages: list[dict[str, str]],
    model: str,
    ollama_url: str,
    temperature: float,
    json_answer: bool = False,
) -> str:
    url = ollama_url.rstrip("/") + "/api/chat"
    request_payload: dict[str, Any] = {
        "model": model,
        "messages": messages,
        "stream": False,
        "think": False,
        "options": {"temperature": temperature, "num_predict": 1200},
    }
    if json_answer:
        request_payload["format"] = {
            "type": "object",
            "properties": {
                "answer": {"type": "string"},
                "citations": {
                    "type": "array",
                    "items": {"type": "integer"},
                },
            },
            "required": ["answer", "citations"],
        }
    response = requests.post(
        url,
        json=request_payload,
        timeout=180,
    )
    response.raise_for_status()
    payload = response.json()
    message = payload.get("message") or {}
    content = message.get("content")
    if not content:
        raise RuntimeError(f"Ollama returned an unexpected response: {payload}")
    text = str(content).strip()
    if json_answer:
        try:
            parsed = json.loads(text)
        except json.JSONDecodeError as exc:
            raise RuntimeError(f"Ollama returned invalid JSON: {text[:500]}") from exc
        answer = parsed.get("answer") if isinstance(parsed, dict) else None
        if not isinstance(answer, str) or not answer.strip():
            raise RuntimeError(f"Ollama JSON response has no answer: {parsed}")
        answer = answer.strip()
        raw_citations = parsed.get("citations")
        citations = (
            sorted({item for item in raw_citations if isinstance(item, int) and item > 0})
            if isinstance(raw_citations, list)
            else []
        )
        if citations and not re.search(r"\[\d+\]", answer):
            answer = f"{answer}\n\nNguồn: " + ", ".join(f"[{item}]" for item in citations)
        return answer
    return text


def valid_citation_indexes(answer: str, chunk_count: int) -> set[int]:
    return {
        int(index)
        for index in re.findall(r"\[(\d+)\]", answer or "")
        if 1 <= int(index) <= chunk_count
    }


def has_reasoning_leak(answer: str) -> bool:
    lowered = (answer or "").lower()
    markers = (
        "okay, let's",
        "the user is asking",
        "first, i need",
        "let me check",
        "starting with",
        "which translates to",
        "the context has",
        "i need to",
    )
    return any(marker in lowered for marker in markers)


def has_forbidden_advice(answer: str) -> bool:
    normalized = normalize_for_match(answer)
    markers = (
        "ban nen",
        "toi khuyen",
        "tot nhat",
        "lua chon phu hop",
        "nen lua chon",
    )
    return any(marker in normalized for marker in markers)


def extract_legal_identifiers(text: str) -> set[str]:
    patterns = (
        r"\b\d{1,4}/\d{4}/[A-ZĐ]+(?:-[A-ZĐ]+)?\b",
        r"\b\d{1,4}/VBHN-[A-ZĐ]+\b",
        r"\bĐiều\s+\d+[a-zA-Z]?\b",
        r"\bMẫu\s+số\s+\d+\b",
        r"\bPhụ\s+lục\s+[IVX]+\b",
    )
    found: set[str] = set()
    for pattern in patterns:
        found.update(re.findall(pattern, text or "", flags=re.IGNORECASE))
    return {re.sub(r"\s+", " ", item).strip() for item in found}


def unsupported_legal_identifiers(
    answer: str,
    chunks: list[RetrievedChunk],
) -> set[str]:
    context = build_context(chunks, max_chars=10_000_000)
    supported = {normalize_for_match(item) for item in extract_legal_identifiers(context)}
    return {
        item
        for item in extract_legal_identifiers(answer)
        if normalize_for_match(item) not in supported
    }


def answer_passes_grounding_checks(
    answer: str,
    chunks: list[RetrievedChunk],
) -> bool:
    return bool(valid_citation_indexes(answer, len(chunks))) and not (
        has_reasoning_leak(answer)
        or has_forbidden_advice(answer)
        or unsupported_legal_identifiers(answer, chunks)
    )


def call_grounded_ollama(
    question: str,
    chunks: list[RetrievedChunk],
    max_context_chars: int,
    model: str,
    ollama_url: str,
    temperature: float,
) -> str:
    """Generate an answer and retry once if chunk citations are missing."""
    messages = build_messages(question, chunks, max_context_chars)
    answer = call_ollama(messages, model, ollama_url, temperature, json_answer=True)
    if answer_passes_grounding_checks(answer, chunks):
        return answer

    context = build_context(chunks, max_context_chars)
    retry_messages = [
        {
            "role": "system",
            "content": (
                "/no_think\nChỉ xuất đáp án cuối cùng bằng tiếng Việt. Không xuất suy luận, "
                "phân tích, bản dịch hoặc lời dẫn. Chỉ dùng CONTEXT và phải có citation chunk hợp lệ."
            ),
        },
        {
            "role": "user",
            "content": (
                f"CONTEXT:\n{context}\n\nCÂU HỎI:\n{question}\n\n"
                "Trả lời trực tiếp trong tối đa 250 từ. Đặt [1], [2], ... ngay sau thông tin "
                "tương ứng. Không tạo citation lớn hơn số chunk. Không trả lời người dùng nên "
                "hay không nên làm gì. Không thêm số điều, khoản, điểm hoặc văn bản không xuất "
                "hiện nguyên văn trong CONTEXT. Không tư vấn hoặc suy đoán.\n/no_think"
            ),
        },
    ]
    retried_answer = call_ollama(
        retry_messages,
        model,
        ollama_url,
        0.0,
        json_answer=True,
    )
    if answer_passes_grounding_checks(retried_answer, chunks):
        return retried_answer
    return FALLBACK_ANSWER


def print_retrieved(chunks: list[RetrievedChunk]) -> None:
    print("\nNguồn truy xuất:")
    for chunk in chunks:
        print(f"  {format_source(chunk)} | score={chunk.score:.4f} | chunk_id={chunk.chunk_id}")


def answer_question(args: argparse.Namespace, model: Any, manifest: dict[str, Any], documents: list[dict[str, Any]], vectors: np.ndarray, question: str) -> None:
    result = guarded_retrieve(
        question,
        model,
        manifest["embedding_model"],
        documents,
        vectors,
        args.top_k,
    )
    chunks = result.chunks
    if not result.accepted:
        print("\nTrả lời:")
        print(FALLBACK_ANSWER)
        return

    if result.query.retrieval_question != result.query.original_question:
        print(f"\nTruy vấn retrieval đã chuẩn hóa: {result.query.retrieval_question}")
    print_retrieved(chunks)

    if args.retrieve_only:
        print("\nCác đoạn liên quan:")
        for chunk in chunks:
            preview = chunk.text.strip().replace("\n", " ")
            print(f"\n{format_source(chunk)}\n{preview[:1000]}")
        return

    try:
        answer = call_grounded_ollama(
            question,
            chunks,
            args.max_context_chars,
            args.model,
            args.ollama_url,
            args.temperature,
        )
    except requests.RequestException as exc:
        raise RuntimeError(
            f"Cannot call Qwen via Ollama at {args.ollama_url}. "
            f"Start Ollama and run: ollama pull {args.model}"
        ) from exc

    print("\nTrả lời:")
    print(answer)


def chat_loop(args: argparse.Namespace, model: Any, manifest: dict[str, Any], documents: list[dict[str, Any]], vectors: np.ndarray) -> None:
    print("RAG chatbot đã sẵn sàng. Gõ 'exit' để thoát.")
    while True:
        question = input("\nBạn hỏi: ").strip()
        if question.lower() in {"exit", "quit", "q"}:
            break
        if not question:
            continue
        answer_question(args, model, manifest, documents, vectors, question)


def main() -> None:
    configure_console_encoding()
    args = parse_args()
    manifest, documents, vectors = load_vectorstore(Path(args.vectorstore))
    model = load_embedding_model(manifest["embedding_model"])

    if args.question:
        answer_question(args, model, manifest, documents, vectors, args.question)
    else:
        chat_loop(args, model, manifest, documents, vectors)


if __name__ == "__main__":
    try:
        main()
    except (FileNotFoundError, RuntimeError, ValueError) as exc:
        raise SystemExit(str(exc)) from exc
